base_url = "https://jaehyeonleeweb.github.io/j-h-2026"
title = "J-H"
default_language = "en"
build_search_index = true
generate_feeds = false
ignored_content = ["content/shop/**"]


[markdown]
bottom_footnotes = true

[languages]
[languages.kr]
title = "제이대시에이치"